os: Visual Studio 2015

environment:
  GITHUB_TOKEN:
    secure: BdKySTKbuABSFa1ar5ZQ2/Ud+WHNbmYHszUyd4twaqg=

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> web\package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> web\package.json         # npm cache
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - web\node_modules -> web\package.json
  - web\jspm_packages -> web\config.js
  
services:
  - mongodb

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%  
  - npm install -g gulp
  - npm install -g jspm  
  - jspm config registries.github.auth %GITHUB_TOKEN%
    
before_build:
  - nuget restore

build:
  parallel: true
  
after_build:
 - ps: .\jsbuild.ps1