os: Visual Studio 2015

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - npm config set loglevel info
  - ps: .\Install-MongoDb-On-AppVeyor.ps1

before_build:
  - nuget restore
  
after_build:
 - ps: .\jsbuild.ps1