os: Visual Studio 2015

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%    
  - ps: .\Install-MongoDb-On-AppVeyor.ps1
  - npm install -g gulp
  - npm install -g jspm

before_build:
  - nuget restore
  
after_build:
 - ps: .\jsbuild.ps1