os: Visual Studio 2015

environment:
  GITHUB_TOKEN:
    secure: BdKySTKbuABSFa1ar5ZQ2/Ud+WHNbmYHszUyd4twaqg=

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> web\package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> web\package.json         # npm cache
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - web\node_modules -> web\package.json
  - web\jspm_packages -> web\config.js
  
services:
  - mongodb

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%  
  - npm install -g gulp
  - npm install -g jspm  
  - jspm config registries.github.auth %GITHUB_TOKEN%
    
before_build:
  - nuget restore

build:
  parallel: true
  publish_wap: true
 
deploy:
  provider: WebDeploy
  server: https://celery.scm.azurewebsites.net:443/msdeploy.axd?site=Celery
  website: "Celery"
  username: $Celery
  password:
    secure: 6YzI6R8tSEO3kfY1eUu/4T+nvFt8G160lI6kx3B08a+DPNW9P98frXN2df5PpHCKXvl0j82Eq8EUHuLAqO7Hmw==
  ntlm: false
  remove_files: false
