//****************************************************************
//  Generated by:  ToTypeScriptD
//  Website:       http://github.com/ToTypeScriptD/ToTypeScriptD
//  Version:       v0.1.5081.42854 - SHA1:66c203d - Debug
//  Date:          12/06/15 21:14:26
//
//  Assemblies:
//    Data.dll
//
//****************************************************************



declare module Data.Dto {

    export interface Foo {
    }

    export interface Food {
        name: string;
        category: string;
        strings: string[];
        foos: Data.Dto.Foo[];
        fruits: Data.Dto.Fruit;
    }

    enum Fruit {
        orange,
        pear,
        apple
    }

}

